### ISSUE TITLE
Bowser Timers

### ISSUE THREAD

**Issue by d12rjb4n4n4z** [Dotsarecool/SMWPracticeCart#1]
First of all I just wanted to say thanks for this practice cart Dots! It's awesome. Anyways, I don't know if you know this already but it seems like some timers for Bowser don't get reset when you reset that room with L+R. For example, sometimes he throws down some Mechakoopas or a Big Steely at the very beginning while the clown car is still making its way down. I think it might be because he was about to throw them when you reset the room. Also, sometimes Bowser goes off into the clown car and the fire animation starts after only one hit instead of two. I think the cart remembers if you hit Bowser before you reset the room. I don't know if this is on your radar or not so I thought I'd let you know. I read the bugs you listed and saw this:

Some room resets cause enemies to spawn facing the wrong direction--this was trivial to fix for a whole level reset but will be difficult to fix on a per-level-entrance basis.

I don't know if this includes what I just mentioned with Bowser. Also, I don't know if this includes boo rings positions not getting restored to the original position when you entered a room once you reset it. I don't know if that can be done but it would be nice in practicing the second room in Donut Secret House. Some of the clipping techniques in the first room aren't very consistent so it would be hard to practice the second room if the boo rings change position on each room reset. For example the small mario only clip where you spin jump through the stairs. I have no idea how to do the second room cause every time I get that clip I only have one shot at the boo ring position of the next room. You don't lose anything going for that clip so I'll try it every time. But when I get the clip, it would be nice to know how the second room would be.

Thanks for everything Dots! I really appreciate it. Keep up the good work :)

**Comment by IsoFrieze** [comment]
Everything regarding Bowser fixed in v6.
Enemy direction spawning via room resets won't be fixed anytime soon since it hasn't been that much of a problem.
There is an issue with keeping a boo ring/cloud's data via room reset. A temporary fix would be to know that boo ring/cloud positions are reset to what they were at the beginning of a level, even for room resets. Using this fact along with start+select lets you set up a boo ring in an appropriate position for any room.
