### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by kevinvanrijn** [Dotsarecool/SMWPracticeCart#4]
Dotsarecool.com is currently down (ERR_CONNECTION_REFUSED) making this hack unavailable. 

Would it be possible to provide it on the [releases tab](https://github.com/Dotsarecool/SMWPracticeCart/releases) in addition to the website to avoid this in the future?

**Comment by kevinvanrijn** [comment]
Dotsarecool.com is back up. Would still like a backup download of this somewhere.

**Comment by IsoFrieze** [comment]
I can't host the patched rom here for copyright reasons. I could host a BPS patch though. The source is available so I think I'll just provide some instructions on how to assemble the patch from the source.

**Comment by kevinvanrijn** [comment]
It has been a while. Please still do this once you find the time for it.

**Comment by IsoFrieze** [comment]
I created a readme file that has instructions how to compile the ROM from the source provided.
