### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by philipbower122** [Dotsarecool/SMWPracticeCart#5]
May I ask how you compile this into the smc. file?

**Comment by IsoFrieze** [comment]
You don't. It's a patch for an already existing SMW ROM. You can find out how to do that in the [readme file](https://github.com/Dotsarecool/SMWPracticeCart/blob/master/README.md).
Alternatively, you can just download an already patched version from [my website](http://www.dotsarecool.com/twitch/practice.html).

**Comment by philipbower122** [comment]
Ah I see ok. Yep it works i found it. No worries. Thanks. For a great ROM :)
